# ===============================
# Application
# ===============================
spring.application.name=quiztech

# ===============================
# Database Configuration
# ===============================
# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/quiztech_database?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# JWT
# ===============================
jwt.secret=quiztech_super_secret_key_2026_hightech_secret_key_123456789
jwt.expiration=86400000

# ===============================
# Server
# ===============================
server.port=8080

# ===============================
# Logging
# ===============================
logging.level.org.springframework.security=DEBUG
logging.level.org.hibernate.SQL=DEBUG